name: "CI practise"

on:
  push:
    branches:
      - main  

jobs: 
  codeInteg:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: set image version
        run: echo "VERSION=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV
      
      - name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker image build & push
        uses: docker/build-push-action@v4
        with: 
          context: ./src/frontend
          push: true
          tags: heyrohhh/frontend:${{ env.VERSION }}

      
      - name: aws login
        uses : aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
     
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6
       
      - name: Terraform apply
        run: |
           cd terraform
           terraform init
           terraform apply -var="frontend_image=heyrohhh/frontend:${{ env.VERSION }}" -auto-approve

         
